apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  generateName: container-kill-podtato-hats-podtato-head-hats-
  labels:
    instance_id: e6e8e3e4-19f1-4185-b9a6-87210f02e2f4
    workflow_name: custom-chaos-workflow-1637841048
spec:
  engineState: active
  appinfo:
    appns: podtato-head
    applabel: app.kubernetes.io/component=podtato-head-hats
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "20"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: CONTAINER_RUNTIME
              value: docker
            - name: SOCKET_PATH
              value: /var/run/docker.sock
            - name: PODS_AFFECTED_PERC
              value: ""
            - name: TARGET_CONTAINER
              value: ""
